# Modified version of .tmux.conf from the awesome book  "tmux: Productive
# Mouse-Free Development"
#
# https://pragprog.com/book/bhtmux/tmux
#
# Remap prfix to CTRL-a:
set -g prefix C-a
# Free up CTRL-b:
unbind C-b
# Reduce escape-time for Vim's benefit:
set -s escape-time 1
# Base both window and pane indexes at 1 (instead of zero):
set -g base-index 1
setw -g pane-base-index 1
# Shortcut for tmux 'source-file':
bind r source-file ~/.tmux.conf\; display "Reloaded!"
# Make sure CTRL-a can still be used elsewhere:
bind C-a send-prefix
# Build in shortcuts for horizontal and vertical splits:
bind | split-window -h
bind - split-window -v
# Imitate Vim navigation:
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Home-row friendly keybindings for cycling through windows:
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
# Vim-movement-like pane resizing:
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
